# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Set environment variable
ENV OPENAI_API_KEY="your-api-key"

# Run crew.sh to set up the application
RUN ["chmod", "+x", "./crew.sh"]
RUN ./crew.sh

# Run crew_server.py when the container launches
CMD ["python", "src/crew_server.py"]
